In [ ]:
# NumPy is a high performance numerical library that gives Python the power to work with large datasets efficiently. It provides fast, memory optimized arrays and mathematical tools that form the core of
# every machine learning workflow.
# Why NumPy is Important in Machine Learning
# NumPy (Numerical Python) is the foundation of all Machine Learning libraries in Python.
# Almost every ML library - including Pandas, Scikit-Learn, TensorFlow, and PyTorch - is built on top of NumPy.

# Why It's Essential

# . Efficient Computation: Handles large numerical datasets faster than Python lists.
# . Data Representation: ML data (features & labels) are stored as matrices/tensors -> NumPy arrays.
# . Vectorization: Executes math operations on entire arrays without loops.
# . Linear Algebra Support: Used in gradient descent, covariance, matrix multiplication, etc.
# . Integration: Works seamlessly with Pandas, Matplotlib, Scikit-Learn, TensorFlow, and others.
# . If Python is the language of Machine Learning, NumPy is its mathematics engine.

In [2]:
import numpy as np

In [2]:
print(np.__version__)

2.3.5


In [ ]:
# Comparing list and numpy array
import time
import numpy as np

n = 1_000_000  # 1000000

py_list = list(range(n))
np_array = np.arange(n)

# print(len(py_list))
# print(len(np_array))

# print(py_list[0:5])
# print(np_array[0:5])

# Python list
t1 = time.time()
py_result = [x * 2 for x in py_list]   # multiply each element by 2
t2 = time.time()

# NumPy array (same operation)
t3 = time.time()
np_result = np_array * 2               # multiply each element by 2
t4 = time.time()

print("List time:", t2 - t1)
print("NumPy time:", t4 - t3)

List time: 0.06224989891052246
NumPy time: 0.0035262107849121094


In [3]:
arr1 = np.array([1, 2, 3, 4, 5])  # 1D
arr2 = np.array([[1, 2, 3], [4, 5.3, 6]]) # 2D
arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]) # 3D


print("1D array:", arr1)
print("\n2D array:\n", arr2)
print("\n3D array:\n", arr3)

1D array: [1 2 3 4 5]

2D array:
 [[1.  2.  3. ]
 [4.  5.3 6. ]]

3D array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [4]:
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
# Array Attributes
print("Shape:", arr2.shape)
print("Dimensions:", arr2.ndim)
print("Data Type:", arr2.dtype)
print("Data Type:", arr3.dtype)
print("Total Elements:", arr2.size)

Shape: (2, 3)
Dimensions: 2
Data Type: float64
Data Type: int32
Total Elements: 6


In [6]:
## creating special arrays

zeros = np.zeros((3, 3))
ones = np.ones((3, 2))
random_arr = np.random.rand(3, 3)
eye = np.eye(3)
range_arr = np.arange(0, 10, 2)



print(zeros)
print("---------")
print(ones)
print("---------")
print(random_arr)
print("---------")
print(eye)
print("---------")
print(range_arr)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---------
[[1. 1.]
 [1. 1.]
 [1. 1.]]
---------
[[0.2567556  0.187492   0.53702415]
 [0.19542088 0.87462672 0.64863261]
 [0.50315727 0.89998406 0.07667257]]
---------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---------
[0 2 4 6 8]


In [7]:
### indexing and slicing

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print(arr)
print("---------")
print(arr[0,2]) # individual element
print("---------")
print(arr[2])  # row access
print("---------")
print(arr[:, 1])  # column access

[[10 20 30]
 [40 50 60]
 [70 80 90]]
---------
30
---------
[70 80 90]
---------
[20 50 80]


In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Dot Product", np.dot(a, b))
print("Cross Product", np.cross(a, b))

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Dot Product 32
Cross Product [-3  6 -3]


In [9]:
## reshape and flattening 

arr = np.arange(1, 10)
reshaped = arr.reshape(3, 3)
flattened = reshaped.flatten()


print(arr)
print("-----")
print(reshaped)
print("------")
print(flattened)

[1 2 3 4 5 6 7 8 9]
-----
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------
[1 2 3 4 5 6 7 8 9]
